#!/usr/bin/env python
"""
scripts/generate_golden.py
==========================
Generate golden hash untuk tests/test_atmospheric.py.

Jalankan SEKALI di environment referensi (PyTorch version stabil), lalu
copy-paste output ke GOLDEN_HASHES dict di test suite.

Kuantisasi ke uint8 supaya toleran terhadap 1-ULP drift PyTorch.
"""
from __future__ import annotations
import hashlib
import torch

from distortion_library.blur_atmospheric_turbulence_v1 import (
    blur_atmospheric_turbulence_v1 as blur,
)


GOLDEN_CASES = [
    (1, 3, 32, 32, 0.0, 42),
    (1, 3, 32, 32, 0.5, 42),
    (2, 3, 32, 32, 1.0, 42),
    (4, 3, 64, 64, 0.7, 123),
    (1, 1, 32, 32, 0.5, 7),      # grayscale
    (1, 3, 24, 48, 0.5, 11),     # non-square
]


def _case_hash(case) -> str:
    B, C, H, W, sev, seed = case
    torch.manual_seed(0)
    x = torch.rand(B, C, H, W)
    y, _ = blur(x, sev, seed=seed)
    yb = (y * 255).round().clamp(0, 255).to(torch.uint8).numpy().tobytes()
    return hashlib.sha256(yb).hexdigest()


def main() -> None:
    print("# Auto-generated by scripts/generate_golden.py")
    print("# PyTorch", torch.__version__)
    print("GOLDEN_HASHES = {")
    for case in GOLDEN_CASES:
        h = _case_hash(case)
        print(f"    {case}: '{h}',")
    print("}")


if __name__ == "__main__":
    main()
